# Generated by Django 4.2.7 on 2025-09-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('entityType', models.CharField(choices=[('deity', 'Deity'), ('attribute', 'Attribute'), ('rishi', 'Rishi')], db_index=True, max_length=20)),
                ('frequency', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-frequency'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalScore', models.FloatField(db_index=True, default=0.0)),
                ('conjunctionScore', models.FloatField(default=0.0)),
                ('hymnCooccurrenceScore', models.FloatField(default=0.0)),
                ('indirectScore', models.FloatField(default=0.0)),
                ('hymnReferences', models.JSONField(blank=True, default=list)),
                ('conjunctionContexts', models.JSONField(blank=True, default=list)),
                ('entity1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_entity1', to='api.entity')),
                ('entity2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_entity2', to='api.entity')),
            ],
            options={
                'ordering': ['-finalScore'],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name'], name='api_entity_name_2f09f5_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entityType'], name='api_entity_entityT_0e9828_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['-frequency'], name='api_entity_frequen_f9e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['entity1', '-finalScore'], name='api_relatio_entity1_c5e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['entity2', '-finalScore'], name='api_relatio_entity2_7c3db6_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['-finalScore'], name='api_relatio_finalSc_d9167d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('entity1', 'entity2')},
        ),
    ]
